const REQUEST_AVAILABILITY = 'REQUEST_AVAILABILITY';
const RECEIVED_AVAILABILITY = 'RECEIVED_AVAILABILITY';
const BOOK_SLOT = 'BOOK_SLOT';

export {
	RECEIVED_AVAILABILITY,
	REQUEST_AVAILABILITY,
	BOOK_SLOT,
};
